DROP TABLE IF EXISTS works;

DROP TABLE IF EXISTS images;

CREATE TABLE works (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  description VARCHAR(1000),
);

CREATE TABLE images (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author VARCHAR(100),
  alt VARCHAR(1000),
  url VARCHAR,
);